defaultConfiguration = {
    'default': '#cccccc',
    'background': '#252525',
    'selectiontext': '#ffffff',
    'selectionbackground': '#0b5aaf',
    'operator': '#cccccc',
    'number': '#ffc600',
    'string': '#adf195',
    'comment': '#666666',
    'keyword': '#f86d7c', 
    'error': '#ff0000',
    'warning': '#ff7315',
    'info': '#4f4f4f',
    'hint': '#008bdB',
    'findselectionbackground': '#8d7600',
    'matchingwordbackground': '#555555',
    'builtin': '#84d6f7',
    'whitespace': '#555555',
    'activeline': '#2d3241',
    'debuggercurrentline': '#2a3c4c',
    'debuggererrorline': '#4c2a2a',
    'method': '#fdfbac',
    'property': '#61a1f1',
    'nil': '#ffc600',
    'bool': '#ffc600',
    'function': '#f86d7c',
    'local': '#f86d7c',
    'self': '#f86d7c',
    'luaukeyword': '#f86d7c',
    'functionname': '#fdfbac',
    'todo': '#666666',
    'ruler': '#666666',
    'type': '#00fffc',
    'bracket': '#cccccc',
    'docviewcodebackground': '#424242',
    'menuprimarytext': '#ffffff',
    'menusecondarytext': '#666666',
    'menuselectedtext': '#ffffff',
    'menubackground': '#2e2e2e',
    'menuselectedbackground': '#265aa9',
    'menuscrollbarbackground': '#2e2e2e',
    'menuscrollbarhandle': '#b3b3b3',
    'indentationruler': '#666666'
}

studioNames = {
    'default': 'Text Color',
    'background': 'Background Color',
    'selectiontext': 'Selection Color',
    'selectionbackground': 'Selection Background Color',
    'operator': 'Operator Color',
    'number': 'Number Color',
    'string': 'String Color',
    'comment': 'Comment Color',
    'keyword': 'Keyword Color', 
    'error': 'Error Color',
    'warning': 'Warning Color',
    'info': 'Information Color',
    'hint': 'Hint Color',
    'findselectionbackground': 'Find Selection Background Color',
    'matchingwordbackground': 'Matching Word Background Color',
    'builtin': 'Built-in Function Color',
    'whitespace': 'Whitespace Color',
    'activeline': 'Current Line Highlight Color',
    'debuggercurrentline': 'Debugger Current Line Color',
    'debuggererrorline': 'Debugger Error Line Color',
    'method': 'Local Method Color',
    'property': 'Local Property Color',
    'nil': '"nil" Color',
    'bool': 'Bool Color',
    'function': '"function" Color',
    'local': '"local" Color',
    'self': '"self" Color',
    'luaukeyword': 'Luau Keyword Color',
    'functionname': 'Function Name Color',
    'todo': 'TODO Color',
    'ruler': 'Script Ruler Color',
    'type': 'Type Color',
    'bracket': 'Script Bracket Color',
    'docviewcodebackground': 'Documentation Code Block Background Color',
    'menuprimarytext': 'Menu Primary Text Color',
    'menusecondarytext': 'Menu Secondary Text Color',
    'menuselectedtext': 'Menu Selected Text Color',
    'menubackground': 'Menu Item Background',
    'menuselectedbackground': 'Selected Menu Item Background',
    'menuscrollbarbackground': 'Script Editor Scrollbar Background',
    'menuscrollbarhandle': 'Script Editor Scrollbar Handle',
    'indentationruler': 'Indentation Ruler Color'
}

registryNames = {v: k for k, v in studioNames.items()}